// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: collector.proto
#ifndef GRPC_collector_2eproto__INCLUDED
#define GRPC_collector_2eproto__INCLUDED

#include "collector.pb.h"

#include <functional>
#include <grpc/impl/codegen/port_platform.h>
#include <grpcpp/impl/codegen/async_generic_service.h>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/client_context.h>
#include <grpcpp/impl/codegen/completion_queue.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

class YuzuCollector final {
 public:
  static constexpr char const* service_full_name() {
    return "YuzuCollector";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status ReportTimer(::grpc::ClientContext* context, const ::TimerTelemetry& request, ::TelemetryReply* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::TelemetryReply>> AsyncReportTimer(::grpc::ClientContext* context, const ::TimerTelemetry& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::TelemetryReply>>(AsyncReportTimerRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::TelemetryReply>> PrepareAsyncReportTimer(::grpc::ClientContext* context, const ::TimerTelemetry& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::TelemetryReply>>(PrepareAsyncReportTimerRaw(context, request, cq));
    }
    virtual ::grpc::Status ReportDataSize(::grpc::ClientContext* context, const ::DataSizeTelemetry& request, ::TelemetryReply* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::TelemetryReply>> AsyncReportDataSize(::grpc::ClientContext* context, const ::DataSizeTelemetry& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::TelemetryReply>>(AsyncReportDataSizeRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::TelemetryReply>> PrepareAsyncReportDataSize(::grpc::ClientContext* context, const ::DataSizeTelemetry& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::TelemetryReply>>(PrepareAsyncReportDataSizeRaw(context, request, cq));
    }
    class experimental_async_interface {
     public:
      virtual ~experimental_async_interface() {}
      virtual void ReportTimer(::grpc::ClientContext* context, const ::TimerTelemetry* request, ::TelemetryReply* response, std::function<void(::grpc::Status)>) = 0;
      virtual void ReportTimer(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::TelemetryReply* response, std::function<void(::grpc::Status)>) = 0;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void ReportTimer(::grpc::ClientContext* context, const ::TimerTelemetry* request, ::TelemetryReply* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      #else
      virtual void ReportTimer(::grpc::ClientContext* context, const ::TimerTelemetry* request, ::TelemetryReply* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      #endif
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void ReportTimer(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::TelemetryReply* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      #else
      virtual void ReportTimer(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::TelemetryReply* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      #endif
      virtual void ReportDataSize(::grpc::ClientContext* context, const ::DataSizeTelemetry* request, ::TelemetryReply* response, std::function<void(::grpc::Status)>) = 0;
      virtual void ReportDataSize(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::TelemetryReply* response, std::function<void(::grpc::Status)>) = 0;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void ReportDataSize(::grpc::ClientContext* context, const ::DataSizeTelemetry* request, ::TelemetryReply* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      #else
      virtual void ReportDataSize(::grpc::ClientContext* context, const ::DataSizeTelemetry* request, ::TelemetryReply* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      #endif
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void ReportDataSize(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::TelemetryReply* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      #else
      virtual void ReportDataSize(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::TelemetryReply* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      #endif
    };
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    typedef class experimental_async_interface async_interface;
    #endif
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    async_interface* async() { return experimental_async(); }
    #endif
    virtual class experimental_async_interface* experimental_async() { return nullptr; }
  private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::TelemetryReply>* AsyncReportTimerRaw(::grpc::ClientContext* context, const ::TimerTelemetry& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::TelemetryReply>* PrepareAsyncReportTimerRaw(::grpc::ClientContext* context, const ::TimerTelemetry& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::TelemetryReply>* AsyncReportDataSizeRaw(::grpc::ClientContext* context, const ::DataSizeTelemetry& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::TelemetryReply>* PrepareAsyncReportDataSizeRaw(::grpc::ClientContext* context, const ::DataSizeTelemetry& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel);
    ::grpc::Status ReportTimer(::grpc::ClientContext* context, const ::TimerTelemetry& request, ::TelemetryReply* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::TelemetryReply>> AsyncReportTimer(::grpc::ClientContext* context, const ::TimerTelemetry& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::TelemetryReply>>(AsyncReportTimerRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::TelemetryReply>> PrepareAsyncReportTimer(::grpc::ClientContext* context, const ::TimerTelemetry& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::TelemetryReply>>(PrepareAsyncReportTimerRaw(context, request, cq));
    }
    ::grpc::Status ReportDataSize(::grpc::ClientContext* context, const ::DataSizeTelemetry& request, ::TelemetryReply* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::TelemetryReply>> AsyncReportDataSize(::grpc::ClientContext* context, const ::DataSizeTelemetry& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::TelemetryReply>>(AsyncReportDataSizeRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::TelemetryReply>> PrepareAsyncReportDataSize(::grpc::ClientContext* context, const ::DataSizeTelemetry& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::TelemetryReply>>(PrepareAsyncReportDataSizeRaw(context, request, cq));
    }
    class experimental_async final :
      public StubInterface::experimental_async_interface {
     public:
      void ReportTimer(::grpc::ClientContext* context, const ::TimerTelemetry* request, ::TelemetryReply* response, std::function<void(::grpc::Status)>) override;
      void ReportTimer(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::TelemetryReply* response, std::function<void(::grpc::Status)>) override;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void ReportTimer(::grpc::ClientContext* context, const ::TimerTelemetry* request, ::TelemetryReply* response, ::grpc::ClientUnaryReactor* reactor) override;
      #else
      void ReportTimer(::grpc::ClientContext* context, const ::TimerTelemetry* request, ::TelemetryReply* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      #endif
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void ReportTimer(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::TelemetryReply* response, ::grpc::ClientUnaryReactor* reactor) override;
      #else
      void ReportTimer(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::TelemetryReply* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      #endif
      void ReportDataSize(::grpc::ClientContext* context, const ::DataSizeTelemetry* request, ::TelemetryReply* response, std::function<void(::grpc::Status)>) override;
      void ReportDataSize(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::TelemetryReply* response, std::function<void(::grpc::Status)>) override;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void ReportDataSize(::grpc::ClientContext* context, const ::DataSizeTelemetry* request, ::TelemetryReply* response, ::grpc::ClientUnaryReactor* reactor) override;
      #else
      void ReportDataSize(::grpc::ClientContext* context, const ::DataSizeTelemetry* request, ::TelemetryReply* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      #endif
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void ReportDataSize(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::TelemetryReply* response, ::grpc::ClientUnaryReactor* reactor) override;
      #else
      void ReportDataSize(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::TelemetryReply* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      #endif
     private:
      friend class Stub;
      explicit experimental_async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class experimental_async_interface* experimental_async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class experimental_async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::TelemetryReply>* AsyncReportTimerRaw(::grpc::ClientContext* context, const ::TimerTelemetry& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::TelemetryReply>* PrepareAsyncReportTimerRaw(::grpc::ClientContext* context, const ::TimerTelemetry& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::TelemetryReply>* AsyncReportDataSizeRaw(::grpc::ClientContext* context, const ::DataSizeTelemetry& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::TelemetryReply>* PrepareAsyncReportDataSizeRaw(::grpc::ClientContext* context, const ::DataSizeTelemetry& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_ReportTimer_;
    const ::grpc::internal::RpcMethod rpcmethod_ReportDataSize_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status ReportTimer(::grpc::ServerContext* context, const ::TimerTelemetry* request, ::TelemetryReply* response);
    virtual ::grpc::Status ReportDataSize(::grpc::ServerContext* context, const ::DataSizeTelemetry* request, ::TelemetryReply* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_ReportTimer : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_ReportTimer() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_ReportTimer() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ReportTimer(::grpc::ServerContext* /*context*/, const ::TimerTelemetry* /*request*/, ::TelemetryReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestReportTimer(::grpc::ServerContext* context, ::TimerTelemetry* request, ::grpc::ServerAsyncResponseWriter< ::TelemetryReply>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_ReportDataSize : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_ReportDataSize() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_ReportDataSize() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ReportDataSize(::grpc::ServerContext* /*context*/, const ::DataSizeTelemetry* /*request*/, ::TelemetryReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestReportDataSize(::grpc::ServerContext* context, ::DataSizeTelemetry* request, ::grpc::ServerAsyncResponseWriter< ::TelemetryReply>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_ReportTimer<WithAsyncMethod_ReportDataSize<Service > > AsyncService;
  template <class BaseClass>
  class ExperimentalWithCallbackMethod_ReportTimer : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithCallbackMethod_ReportTimer() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodCallback(0,
          new ::grpc_impl::internal::CallbackUnaryHandler< ::TimerTelemetry, ::TelemetryReply>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::TimerTelemetry* request, ::TelemetryReply* response) { return this->ReportTimer(context, request, response); }));}
    void SetMessageAllocatorFor_ReportTimer(
        ::grpc::experimental::MessageAllocator< ::TimerTelemetry, ::TelemetryReply>* allocator) {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
    #else
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::experimental().GetHandler(0);
    #endif
      static_cast<::grpc_impl::internal::CallbackUnaryHandler< ::TimerTelemetry, ::TelemetryReply>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~ExperimentalWithCallbackMethod_ReportTimer() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ReportTimer(::grpc::ServerContext* /*context*/, const ::TimerTelemetry* /*request*/, ::TelemetryReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* ReportTimer(
      ::grpc::CallbackServerContext* /*context*/, const ::TimerTelemetry* /*request*/, ::TelemetryReply* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* ReportTimer(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::TimerTelemetry* /*request*/, ::TelemetryReply* /*response*/)
    #endif
      { return nullptr; }
  };
  template <class BaseClass>
  class ExperimentalWithCallbackMethod_ReportDataSize : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithCallbackMethod_ReportDataSize() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodCallback(1,
          new ::grpc_impl::internal::CallbackUnaryHandler< ::DataSizeTelemetry, ::TelemetryReply>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::DataSizeTelemetry* request, ::TelemetryReply* response) { return this->ReportDataSize(context, request, response); }));}
    void SetMessageAllocatorFor_ReportDataSize(
        ::grpc::experimental::MessageAllocator< ::DataSizeTelemetry, ::TelemetryReply>* allocator) {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(1);
    #else
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::experimental().GetHandler(1);
    #endif
      static_cast<::grpc_impl::internal::CallbackUnaryHandler< ::DataSizeTelemetry, ::TelemetryReply>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~ExperimentalWithCallbackMethod_ReportDataSize() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ReportDataSize(::grpc::ServerContext* /*context*/, const ::DataSizeTelemetry* /*request*/, ::TelemetryReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* ReportDataSize(
      ::grpc::CallbackServerContext* /*context*/, const ::DataSizeTelemetry* /*request*/, ::TelemetryReply* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* ReportDataSize(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::DataSizeTelemetry* /*request*/, ::TelemetryReply* /*response*/)
    #endif
      { return nullptr; }
  };
  #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
  typedef ExperimentalWithCallbackMethod_ReportTimer<ExperimentalWithCallbackMethod_ReportDataSize<Service > > CallbackService;
  #endif

  typedef ExperimentalWithCallbackMethod_ReportTimer<ExperimentalWithCallbackMethod_ReportDataSize<Service > > ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_ReportTimer : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_ReportTimer() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_ReportTimer() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ReportTimer(::grpc::ServerContext* /*context*/, const ::TimerTelemetry* /*request*/, ::TelemetryReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_ReportDataSize : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_ReportDataSize() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_ReportDataSize() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ReportDataSize(::grpc::ServerContext* /*context*/, const ::DataSizeTelemetry* /*request*/, ::TelemetryReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_ReportTimer : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_ReportTimer() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_ReportTimer() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ReportTimer(::grpc::ServerContext* /*context*/, const ::TimerTelemetry* /*request*/, ::TelemetryReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestReportTimer(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_ReportDataSize : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_ReportDataSize() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_ReportDataSize() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ReportDataSize(::grpc::ServerContext* /*context*/, const ::DataSizeTelemetry* /*request*/, ::TelemetryReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestReportDataSize(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class ExperimentalWithRawCallbackMethod_ReportTimer : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithRawCallbackMethod_ReportTimer() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodRawCallback(0,
          new ::grpc_impl::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->ReportTimer(context, request, response); }));
    }
    ~ExperimentalWithRawCallbackMethod_ReportTimer() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ReportTimer(::grpc::ServerContext* /*context*/, const ::TimerTelemetry* /*request*/, ::TelemetryReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* ReportTimer(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* ReportTimer(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #endif
      { return nullptr; }
  };
  template <class BaseClass>
  class ExperimentalWithRawCallbackMethod_ReportDataSize : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithRawCallbackMethod_ReportDataSize() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodRawCallback(1,
          new ::grpc_impl::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->ReportDataSize(context, request, response); }));
    }
    ~ExperimentalWithRawCallbackMethod_ReportDataSize() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ReportDataSize(::grpc::ServerContext* /*context*/, const ::DataSizeTelemetry* /*request*/, ::TelemetryReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* ReportDataSize(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* ReportDataSize(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #endif
      { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_ReportTimer : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_ReportTimer() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler< ::TimerTelemetry, ::TelemetryReply>(std::bind(&WithStreamedUnaryMethod_ReportTimer<BaseClass>::StreamedReportTimer, this, std::placeholders::_1, std::placeholders::_2)));
    }
    ~WithStreamedUnaryMethod_ReportTimer() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status ReportTimer(::grpc::ServerContext* /*context*/, const ::TimerTelemetry* /*request*/, ::TelemetryReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedReportTimer(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::TimerTelemetry,::TelemetryReply>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_ReportDataSize : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_ReportDataSize() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::StreamedUnaryHandler< ::DataSizeTelemetry, ::TelemetryReply>(std::bind(&WithStreamedUnaryMethod_ReportDataSize<BaseClass>::StreamedReportDataSize, this, std::placeholders::_1, std::placeholders::_2)));
    }
    ~WithStreamedUnaryMethod_ReportDataSize() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status ReportDataSize(::grpc::ServerContext* /*context*/, const ::DataSizeTelemetry* /*request*/, ::TelemetryReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedReportDataSize(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::DataSizeTelemetry,::TelemetryReply>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_ReportTimer<WithStreamedUnaryMethod_ReportDataSize<Service > > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_ReportTimer<WithStreamedUnaryMethod_ReportDataSize<Service > > StreamedService;
};


#endif  // GRPC_collector_2eproto__INCLUDED
